[project]
name = "jw_page_navigation"
description = "Jw Web Automation Helper package"
version = "0.1.3"
authors = [
    { name = "Allofmex", email = "allofmex@web.de" }
]
dependencies = [
    "selenium",
    "markdown",
]
